# frozen_string_literal: true

tap 'homebrew/cask'
tap 'pmeinhardt/tools'

cask 'firefox'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'karabiner-elements'
cask 'keepassxc'
cask 'nextcloud'
cask 'postgres-unofficial'
cask 'rectangle'
cask 'slack'
cask 'spotify'

brew 'autoconf'  # for installing erlang
brew 'coreutils'
brew 'gpg'
brew 'pmeinhardt/tools/bun'  # remove brew formulas with leaves
brew 'pmeinhardt/tools/hmm'
brew 'tree'
brew 'watch'
brew 'wget'

brew 'fd'
brew 'gh'
brew 'git'
brew 'jq'
brew 'neovim'
brew 'overmind'
brew 'rg'
brew 'tmux'
brew 'yarn'
brew 'zsh'

brew 'redis'
