# frozen_string_literal: true

cask 'firefox'
cask 'font-jetbrains-mono'
cask 'ghostty'
cask 'karabiner-elements'
cask 'keepassxc'
cask 'rectangle'

brew 'coreutils'
brew 'fd'
brew 'gh'
brew 'git'
brew 'lua'
brew 'jq'
brew 'neovim'
brew 'overmind'
brew 'rg'
brew 'rust'
brew 'tmux'
brew 'wget'
brew 'zsh'

if ENV["HOMEBREW_WORK"]
  cask '1password'
  cask '1password-cli'
  cask 'docker-desktop'
  cask 'firefox@developer-edition'
  cask 'imageoptim'
  cask 'kap'
  cask 'postgres-unofficial'
  cask 'slack'
end
