#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# To debug, uncomment:
# set -o xtrace

SCRIPT_DIR=$(dirname "$0")
# shellcheck source=../script/lib/utils
source "$SCRIPT_DIR/../script/lib/utils"

if ! command -v brew >/dev/null; then
  info "Install homebrew…"
  /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  if [ "$(uname -m)" = "arm64" ]; then
    info "Initialize homebrew shell…"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
else
  info "Update homebrew…"
  brew update
fi

info "Install apps and packages…"
brew bundle \
  --quiet \
  --no-upgrade \
  --file "$SCRIPT_DIR/Brewfile"
