#!/usr/bin/env bash

# Install topics
# Usage: script/install [topic]

set -o errexit
set -o nounset
set -o pipefail

# To debug, uncomment:
# set -o xtrace

SCRIPT_DIR=$(dirname "$0")
# shellcheck source=./lib/utils
source "$SCRIPT_DIR/lib/utils"

DOTS_DIR="$( cd -- "$(dirname "$(dirname "$0")")" >/dev/null 2>&1 ; pwd -P )"
DIR_PATTERN=(! -name ".git" -and ! -name "homebrew" -and ! -name "script")
TOPICS=$(find "$DOTS_DIR" -maxdepth 1 -type d "${DIR_PATTERN[@]}")
readonly DOTS_DIR
readonly DIR_PATTERN
readonly TOPICS

function install_topic() {
  local topic=$1
  cd "$topic"
  find . -maxdepth 1 -name install \
    | while read -r installer; do $installer; done
  find . -maxdepth 1 -name link \
    | while read -r linker; do $linker; done
}

if [ $# -lt 1 ]; then
  info "Install topics…"
  install_topic "$DOTS_DIR/homebrew"
  for topic in ${TOPICS[*]}; do
    install_topic "$topic"
  done
else
  TOPIC=$(echo "$1" |  tr '[A-Z]' '[a-z]')
  info "Install "$TOPIC" topic…"
  install_topic "$DOTS_DIR/$TOPIC"
fi
