#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# To debug, uncomment:
# set -o xtrace

source "../script/lib//utils"

declare ASDF_BIN="$HOME/.asdf"

function add_plugin() {
  local name="$1"
  if ! asdf plugin list | grep -Fq "$name"; then
    asdf plugin add "$name"
  fi
}

if [ ! -d "$ASDF_BIN" ]; then
  brew install asdf
  export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
else
  info "Already installed"
fi

mkdir -p "${ASDF_DATA_DIR:-$HOME/.asdf}/completions"
asdf completion zsh > "${ASDF_DATA_DIR:-$HOME/.asdf}/completions/_asdf"


add_plugin "ruby"
add_plugin "nodejs"
add_plugin "erlang"
add_plugin "elixir"

info "Update asdf plugins…"
asdf plugin update --all
